- name: Copy promtail configuration files
  copy:
    src: "{{ item }}"
    dest: '/tmp/'
  with_items:
  - "promtail-config.yaml"
  - "promtail-daemonset.yaml"
  - "promtail-configmap.yaml"
  - "promtail-serviceaccount.yaml"
  - "promtail-clusterrole.yaml"
  - "promtail-rolebinding.yaml"

- name: Add custom registry into hosts
  lineinfile:
    path: '/etc/hosts'
    line: '10.55.254.42 syngenta.reg'

- name: Create promtail service
  shell: "kubectl apply -f /tmp/{{ item }} --validate=false"
  with_items:
  - "promtail-config.yaml"
  - "promtail-daemonset.yaml"
  - "promtail-configmap.yaml"
  - "promtail-serviceaccount.yaml"
  - "promtail-clusterrole.yaml"
  - "promtail-rolebinding.yaml"


- name: Delete promtail configuration files
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
  - "promtail-config.yaml"
  - "promtail-daemonset.yaml"
  - "promtail-configmap.yaml"
  - "promtail-serviceaccount.yaml"
  - "promtail-clusterrole.yaml"
  - "promtail-rolebinding.yaml"